# Generated by Django 2.2.2 on 2019-06-20 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for customer', primary_key=True, serialize=False, verbose_name='Customer Id')),
                ('C_name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Book Author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home1.Author')),
                ('genre', models.ManyToManyField(help_text='genre of book', to='home1.Genre')),
            ],
        ),
    ]
