# Generated by Django 2.2.2 on 2019-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='purchase_date',
            new_name='C_purchase_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
