# Generated by Django 2.2.2 on 2019-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0003_auto_20190620_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='C_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
