# Generated by Django 2.2.2 on 2019-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0004_customer_c_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='C_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='C_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
